version: '2'

networks:
  §§INSTANCE-monitor-net:
    driver: bridge


volumes:
    prometheus_data: {}
    grafana_data: {}

services:

  §§INSTANCE-prometheus:
    image: prom/prometheus
    container_name: §§INSTANCE-prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
      - '-alertmanager.url=http://alertmanager:9093'
      - '-storage.local.memory-chunks=100000'
    restart: unless-stopped
    expose:
      - 9090
    networks:
      -  §§INSTANCE-monitor-net
    labels:
      org.label-schema.group: "monitoring"
  
  §§INSTANCE-alertmanager:
    image: prom/alertmanager
    container_name: §§INSTANCE-alertmanager
    volumes: 
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '-config.file=/etc/alertmanager/config.yml'
      - '-storage.path=/alertmanager'
    restart: unless-stopped
    expose:
      - 9093
    networks:
      -  §§INSTANCE-monitor-net
    labels:
      org.label-schema.group: "monitoring"

  §§INSTANCE-nodeexporter:
    image: prom/node-exporter
    container_name: §§INSTANCE-nodeexporter
    restart: unless-stopped
    expose:
      - 9100
    networks:
      - §§INSTANCE-monitor-net
    labels:
      org.label-schema.group: "monitoring"

  §§INSTANCE-cadvisor:
    image: google/cadvisor:v0.24.1
    container_name: §§INSTANCE-cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
    expose:
      - 8080
    networks:
      -  §§INSTANCE-monitor-net
    labels:
      org.label-schema.group: "monitoring"
  
  §§INSTANCE-grafana:
    image: grafana/grafana
    container_name: §§INSTANCE-grafana
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - user.config
    restart: unless-stopped
    ports:
      - §§PORT:3000
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
